#!/bin/sh
# /etc/init.d/zram-swap - automatically set up an swapfile with zram
# author bibi21000, last modification 2015.11.13
# author Neil Franklin, last modification 2006.09.15
# This script is copyright ETH Zuerich Physics Departement,
#   use under either modified/non-advertising BSD or GPL license

# this init.d script is intended to be run from rcS.d
#   must run after  mount  of  /var  which may only happen in  S35mountall.sh
#     for this reason we can not build swapfile until after  S35mountall.sh
#       so we also need to use  init.d start|stop  to swapon|off our file
#   and sensibly before the lots of stuff which may happen in  S40networking
#   so we run it as rcS.d/S37zram-swap

### BEGIN INIT INFO
# Provides:          zram-swap
# Required-Start:    $syslog $remote_fs
# Required-Stop:     $syslog $remote_fs
# Should-Start:      $local_fs
# Should-Stop:       $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Autogenerate and use swap with zram
# Description:       Update size in /etc/default/zram-swap
### END INIT INFO

# get ready to work
PATH=/sbin:/bin:/usr/sbin:/usr/bin
export PATH

#32mb by default
ZRAM_SIZE=33554432

#Update the default size in this file
. /etc/default/zram-swap

# what we are
NAME=zram-swap

case "$1" in

  start)
    /bin/echo "Starting ${NAME} ..."

    # load module
    /sbin/modprobe zram

    # create the device
    echo ${ZRAM_SIZE} > /sys/block/zram0/disksize

    # create the the swap and activate it
    /sbin/mkswap /dev/zram0
    /sbin/swapon -p 10 /dev/zram0

    /bin/echo "done."
    ;;


  stop|default-stop)
    /bin/echo -n "Stopping ${NAME} ..."

    # stop the swap
    /sbin/swapoff /dev/zram0

    # unload the module
    /sbin/rmmod zram

    /bin/echo ", done."
    ;;


  restart|reload|force-reload)
    /bin/echo "No daemon to (force-)re[start|load] in ${NAME}"
    ;;


 *)
    /bin/echo "Usage: $0 {start|stop}"

    exit 1
    ;;

esac

exit 0
